# Generated by Django 5.0.1 on 2025-03-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0011_facilityenquiry_packageenquiry_quickserviceenquiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityenquiry',
            name='enquiry_date',
        ),
        migrations.RemoveField(
            model_name='packageenquiry',
            name='enquiry_date',
        ),
        migrations.RemoveField(
            model_name='quickserviceenquiry',
            name='enquiry_date',
        ),
    ]
