# Generated by Django 5.0.1 on 2025-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0012_remove_facilityenquiry_enquiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mpin', models.CharField(max_length=20)),
                ('package_name', models.CharField(max_length=100)),
                ('package_validity_date', models.DateField()),
                ('features_list', models.TextField()),
                ('support_manager_name', models.CharField(max_length=100)),
                ('support_manager_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
