# Generated by Django 5.0.1 on 2025-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0013_customerpackage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPackage',
        ),
    ]
