# Generated by Django 5.0.1 on 2025-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0014_delete_customerpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mpin', models.CharField(max_length=10)),
                ('package_name', models.CharField(max_length=100)),
                ('validity_date', models.DateField()),
                ('package_features', models.TextField()),
                ('support_manager_name', models.CharField(max_length=100)),
                ('support_manager_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
